### ISSUE TITLE
这个字体是不是默认就是比较小？

### ISSUE THREAD

**Issue by diantongren** [NEX-S/Fixedsys-Nerd-Font#1]
使用这个字体的时候，中英文混合时候，中文就会显得特别大

**Comment by NEX-S** [comment]
![Screenshot from 2023-08-27 14-24-56](https://github.com/NEX-S/Fixedsys-Nerd-Font/assets/97107165/d67d3995-1a7d-456c-8f72-90f3dad6e4e1)

我的终端是这样的，您可以参考一下。

**Comment by NEX-S** [comment]
> 使用这个字体的时候，中英文混合时候，中文就会显得特别大

因为 Fixedsys 没有集成中文，所以系统对中文会默认使用 fallback 字体，如果你的 fallback 字体比较大，那就应该会导致中文比较大。
